### PR TITLE
AppVeyor

### PR DESCRIPTION
**Pull request by davidhesselbom**
Here's an interesting example file for using a build matrix: https://github.com/hicknhack-software/QSqlMigrator/blob/master/appveyor.yml

### CODE REVIEW

**Comment by davidhesselbom** [comment]
Looks like I get this for every project:

```
WARNING: Unable to generate output for: C:/projects/freq/lib/justmisc/Makefile.Release [TEMPLATE vclib]
WARNING: Unable to generate output for: C:/projects/freq/lib/justmisc/Makefile.Debug [TEMPLATE vclib]
```

What now?

Also, tons of `WARNING: Failure to find: LICENSE`. What do I need to do to fix this?

**Comment by gustafsson** [comment]
You need to combine qmake -r and qmake -spec win32-g++ into the same command. `qmake -r -spec win32-g++`. A call to qmake generally replaces the results of any previous calls to qmake in the same directory.

The warnings about LICENSE and README.txt can be safely ignored, they are just dead references that hasn't been cleaned out yet. I'll get to it soon unless you beat me to it.

**Comment by davidhesselbom** [comment]
Didn't help. This might be important:

```
WARNING: C:/Qt/5.5/mingw492_32/mkspecs/features/win32/windows.prf:8: Excess colon in front of opening brace.
WARNING: C:/Qt/5.5/mingw492_32/mkspecs/features/qt.prf:101: Excess colon in front of opening brace.
WARNING: C:/Qt/5.5/mingw492_32/mkspecs/features/qt.prf:244: Excess colon in front of opening brace.
WARNING: C:/Qt/5.5/mingw492_32/mkspecs/features/qt.prf:255: Excess colon in front of opening brace.
```

**Comment by gustafsson** [comment]
Right. For `win32-g++` the `lib` template should be used instead of `vclib`. Each of the freq/lib projects .pro files specify `win32:TEMPLATE = vclib`. This is to be used with `-spec win32-msvc20xx` (where xx is one of 05, 08, 10, 12, 13 or 15).  This should say `win32-msvc*: TEMPLATE = vclib` instead.

**Comment by davidhesselbom** [comment]
Okay, so what about

```
win32:CONFIG += debug_and_release
```

? Does that need to be changed into

```
win32-msvc*:CONFIG += debug_and_release
```

as well?

**Comment by gustafsson** [comment]
Yes. This is because the Makefiles produced by Qt are either for Release
builds or Debug builds, not both. With debug_and_release the Visual Studio
projects generated can however support both. Without vclib the expected
output is makefiles and with debug_and_release two makefiles are produced,
but I don't see how that makes things easier.
tis 22 sep 2015 kl. 23:19 skrev David Hesselbom notifications@github.com:

**Comment by davidhesselbom** [comment]
Fixed it, but I still get 

```
WARNING: C:/Qt/5.5/mingw492_32/mkspecs/features/win32/windows.prf:8: Excess colon in front of opening brace.
WARNING: C:/Qt/5.5/mingw492_32/mkspecs/features/qt.prf:101: Excess colon in front of opening brace.
WARNING: C:/Qt/5.5/mingw492_32/mkspecs/features/qt.prf:244: Excess colon in front of opening brace.
WARNING: C:/Qt/5.5/mingw492_32/mkspecs/features/qt.prf:255: Excess colon in front of opening brace.
```

**Comment by davidhesselbom** [comment]
Hm, I guess I'll need it in `src/src.pro` too, eh?

**Comment by davidhesselbom** [comment]
Also

```
In file included from blocking_queue.cpp:2:0:
../backtrace/exceptionassert.h:6:28: fatal error: boost/format.hpp: No such file or directory
 #include <boost/format.hpp>
```

That file seems to be avaiable in `3rdparty\windows\boost`, so what do I need to do to help the compiler find it?

**Comment by gustafsson** [comment]
I wouldn't worry about those Qt internals (qt.prf, windows.prf). They do indeed have excess colons. Don't know why they're there, or why qmake warns about them.

`features/buildflags.prf` has a line `ios: INCLUDEPATH += $$_PRO_FILE_PWD_/../../3rdparty/ios/include`, it needs a similar line for win32.

**Comment by davidhesselbom** [comment]
And what path should that "similar line" specify? `$$_PRO_FILE_PWD_/../../3rdparty/windows` contains folders. Is `INCLUDEPATH` "recursive", or do I need to add each of the folders in the `windows` folder, i.e.

```
win32: INCLUDEPATH += $$_PRO_FILE_PWD_/../../3rdparty/windows/boost
...
win32: INCLUDEPATH += $$_PRO_FILE_PWD_/../../3rdparty/windows/zlib/include
```

?

**Comment by gustafsson** [comment]
’#include <boost/format.hpp>’ requires that there is a folder named boost within one of the directories in the includepath. Hence it should point to just 3rdparty/windows.

zlib isn't used for anything in Freq (not yet at least), it was used in Sonic AWE though. Sonic AWE (src.pro) uses sawelibs.prf, which needs to be updated with the new submodule path to build Sonic AWE on windows.

**Comment by gustafsson** [comment]
And to answer your question; no INCLUDEPATH is not recursive
ons 23 sep 2015 kl. 22:05 skrev David Hesselbom notifications@github.com:

**Comment by davidhesselbom** [comment]
Still

```
In file included from blocking_queue.cpp:2:0:
../backtrace/exceptionassert.h:6:28: fatal error: boost/format.hpp: No such file or directory
 #include <boost/format.hpp>
```

despite adding 
`win32: INCLUDEPATH += $$_PRO_FILE_PWD_/../../3rdparty/windows`
to `buildflags.prf`.

**Comment by davidhesselbom** [comment]
I haven't modified `sawelibs.prf` though. Do I need to?

**Comment by gustafsson** [comment]
sawelibs.prf is needed for src.pro, we haven't gotten there yet but src.pro
currently runs all unit tests on the libraries. this is however trivially
copied to quickbase as well.

the feature files (.prf) aren't found by qmake. they shouldn't be found
according tonthe docs either, but it obviously works on osx. anyways,
setting QMAKEFEATURES before running qmake like this should do the trick
(could consider a more elegant solution later):

set QMAKEFEATURES=C:\projects\freq\features
qmake -r -spec ...

or possibly with forslash / instead of backslash \

ons 23 sep 2015 23:15 David Hesselbom notifications@github.com skrev:

**Comment by davidhesselbom** [comment]
Alright, I'll give that a shot. But how should it be done properly? What needs to be done to make qmake find the `.prf` files?

**Comment by davidhesselbom** [comment]
Okay, that did something:

```
WARNING: C:/projects/freq/features/precompile_header_with_all_headers.prf:9: Unescaped backslashes are deprecated
WARNING: C:/projects/freq/features/precompile_header_with_all_headers.prf:10: Unescaped backslashes are deprecated
WARNING: C:/projects/freq/features/precompile_header_with_all_headers.prf:12: Unescaped backslashes are deprecated
WARNING: C:/projects/freq/features/precompile_header_with_all_headers.prf:14: Unescaped backslashes are deprecated
WARNING: C:/projects/freq/features/precompile_header_with_all_headers.prf:14: Unescaped backslashes are deprecated
WARNING: C:/projects/freq/features/precompile_header_with_all_headers.prf:14: Unescaped backslashes are deprecated
WARNING: C:/projects/freq/features/precompile_header_with_all_headers.prf:15: Unescaped backslashes are deprecated
WARNING: C:/projects/freq/features/precompile_header_with_all_headers.prf:15: Unescaped backslashes are deprecated
WARNING: C:/projects/freq/features/precompile_header_with_all_headers.prf:15: Unescaped backslashes are deprecated
```

That whole file is wrapped in a `unix` version block, so I don't know why these warnings are even displayed. Anyway,

```
I../../../../Qt/5.5/mingw492_32/mkspecs/win32-g++  -o tmp/cpu/release/blocking_queue.o blocking_queue.cpp
g++: error: /Ox: No such file or directory
g++: error: /Oi: No such file or directory
g++: error: /Og: No such file or directory
g++: error: /Ot: No such file or directory
g++: error: /Ob2: No such file or directory
g++: error: /GL: No such file or directory
g++: error: /GF: No such file or directory
g++: error: /arch:SSE2: No such file or directory
g++: error: /fp:fast: No such file or directory
g++: error: /MP: No such file or directory
g++: error: /openmp: No such file or directory
Makefile.Release:805: recipe for target 'tmp/cpu/release/blocking_queue.o' failed
mingw32-make[2]: *** [tmp/cpu/release/blocking_queue.o] Error 1
mingw32-make[2]: Leaving directory 'c:/projects/f
```

I guess these flags are specific to the VC++ compiler and g++ has no idea what to do with them? Which ones of these do I need to find a replacement for and which can be removed? And is `/openmp` still relevant even for VC++?

**Comment by gustafsson** [comment]
Moving freq/quick/quick.pro to freq/freq.pro and updating it's contents
accordingly. This requires the qmake command to specify freq.pro as opposed
to sonicawe.pro, i.e "qmake -r -spec sssss freq.pro"

Backslash warning is from reading the .prf file, not from running it.
Ignore it for now, the solution is to have platform specific .prf files in
features/win32, features/macx etc.

The flags (/Ox etc) are VC specific flags from a win32 section in
buildflags. Make a win32-msvc thing instead, as before. These flags aren't
strictly needed, but it makes debugging easier and release builds fast.
tors 24 sep 2015 kl. 21:15 skrev David Hesselbom notifications@github.com:

**Comment by davidhesselbom** [comment]
I care a lot more about ever building than building fast at the moment, so I'll try to do TSTTCPW for g++ and add fancy-ass flags later.

**Comment by davidhesselbom** [comment]
Again, though, is `/openmp` still relevant for VC? Nobody should be running VS 2008 at this point, and I don't think we should optimize for people who spend bajillions of $$$ on a paid version of VS (last time I looked it was something like $5,000).

**Comment by gustafsson** [comment]
I was just about to ask if there was any reason in particular for choosing
mingw over VC, but that answered my question. VC is otherwise preinstalled
on AppVeyor afaik, so qmake -spec win32-msvc2008 is probably easier to run.
Or win32-msvc2015 even.

Sounds good to skip fancy flags until later.
tors 24 sep 2015 kl. 22:20 skrev David Hesselbom notifications@github.com:

**Comment by gustafsson** [comment]
/openmp isn't strictly needed anymore no. Not sure what the performance
gain is of using it is at the moment, if any.
tors 24 sep 2015 kl. 22:23 skrev David Hesselbom notifications@github.com:

**Comment by davidhesselbom** [comment]
No particular reason, no, I just associate VC with VS and different versions of VS being incompatible with their respective vcproj files, I've grown fond of open source stuff, and I don't feel dealing with M$ at the moment. I would have focused entirely on Circle CI at the moment if it wasn't for the fact their servers are messed up right now :/

**Comment by gustafsson** [comment]
Also, express versions of VC are available for $0. VC can open old project
files, but it's a moot poit with Qt as the project files themselves are
temporary and created on the fly for the specific version in question as
part of the build process.

But I really like the idea that it might soon be possible to build freq on
windows without VC, for some reason :)
tors 24 sep 2015 kl. 22:30 skrev Johan Gustafsson <
johan.b.gustafsson@gmail.com>:

**Comment by davidhesselbom** [comment]
> Also, express versions of VC are available for $0

It's not about that... also, I installed VS2013 the other day (because some Atom plugin inexplicably required it to be installed) and it took 10 GB of space and about an hour to install. It's great software, I just don't want to have to be dependent on it if it can be avoided.

Okay, we're making progress! For some reason, it's complaining about things in `c:\mingw\lib\gcc\mingw32\4.8.1\include\c++\...` although I've specified this:

```
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;C:\Qt\Tools\mingw492_32
```

in `appveyor.yml`. I wonder what else I have to do?

**Comment by davidhesselbom** [comment]
Also, do you happen to know whether qmake can generate `.sln` files or just `.vcproj` files? I haven't been able to definitely confirm that to be either true or false.

**Comment by gustafsson** [comment]
Just .vcproj files, you have to make the .sln file yourself. It's a one-off
operation luckily.
tors 24 sep 2015 kl. 22:41 skrev David Hesselbom notifications@github.com:

**Comment by gustafsson** [comment]
MinGW doesn't have support for threads. This sucks. std::mutex and
std::thread are used in a ton of places. However, there seems to be a
polyfil: https://github.com/meganz/mingw-std-threads
tors 24 sep 2015 kl. 22:43 skrev Johan Gustafsson <
johan.b.gustafsson@gmail.com>:

**Comment by gustafsson** [comment]
boost::thread and boost::mutex would also do the trick. None of these
solutions are elegant though.

One solution is do to a mingw specific polyfill and add these 3 files:
3rdparty/mingw/{mutex,thread,condition_variable}

Then add it to INCLUDEPATH for mingw only.

mutex et. al should then look something like this:

#include <../c++/mutex>
#include "mingw-std-mutex/mingw.mutex.h"

Clone the polyfill from meganz into that folder as well as a submodule.
tors 24 sep 2015 kl. 22:50 skrev Johan Gustafsson <
johan.b.gustafsson@gmail.com>:

**Comment by davidhesselbom** [comment]
Seriously? :/ That's a problem... they are defined in the ooc sdk (which has a windows version that supposedly works), which uses gcc as its backend. I could look into how they're used there, or we could use `mingw-std-threads`, yeah.
EDIT: Or boost, sure.

Anyway, on AppVeyor, the folder `4.8.1` is the only folder inside `C:\MinGW\lib\gcc\mingw32\`. I seem to remember you mentioning we need 4.9 or later for C++14. However, I see no mention of C++14 in any of the `.pro` or `.prf` files, only C++11.

**Comment by gustafsson** [comment]
Both gcc and clang are rather permissive in allowing C++14 features even
though you just stated -std=c++11.

In order for c:/Qt/Tools/mingw to take precendence over c:\mingw you have
to prepend it to %PATH% instead of appending.
tors 24 sep 2015 kl. 23:05 skrev David Hesselbom notifications@github.com:

**Comment by davidhesselbom** [comment]
I could find a way to install 4.9, I'm sure, but I'm not sure I need to if we're not using C++14 anyway...

**Comment by davidhesselbom** [comment]
Wait, does `C:\Qt\Tools\mingw` contain the MinGW binaries?

**Comment by gustafsson** [comment]
I thought you had placed a mingw version there :)
I would expect qmake et. al to be in C:\Qt\5.5\mingw492_32\bin
tors 24 sep 2015 kl. 23:10 skrev David Hesselbom notifications@github.com:

**Comment by davidhesselbom** [comment]
Nope, wasn't me. I think AppVeyor comes pre-installed with a bunch of things by popular request and MinGW 4.9, insidet the Qt folder, just happens to be one of those things...

**Comment by gustafsson** [comment]
I.e it's complaining about things in c:\mingw\lib... because mingw492 is
appended after appending c:\mingw\bin to the path.

tors 24 sep 2015 kl. 23:14 skrev Johan Gustafsson <
johan.b.gustafsson@gmail.com>:

**Comment by davidhesselbom** [comment]
Right, so I removed that... appendix. And now it can't find `mingw32-make`. Interesting. I'll add it back, but in the order you suggested.

**Comment by gustafsson** [comment]
I think we should skip adding C:\mingw\bin to the path. Also, the path to
mingw492 binaries is: C:\Qt\Tools\mingw492_32\bin, i.e with a \bin at the
end.
tors 24 sep 2015 kl. 23:18 skrev David Hesselbom notifications@github.com:

**Comment by davidhesselbom** [comment]
Okay. Do I also need to add `C:\Qt\Tools\mingw492_32\lib` to some variable somewhere?

**Comment by gustafsson** [comment]
Nope, the compiler knows where it has its own libs
tors 24 sep 2015 kl. 23:24 skrev David Hesselbom notifications@github.com:

**Comment by davidhesselbom** [comment]
Okay, we're in business! Now we're getting much more interesting errors, lots of things like this:

```
../../../../Qt/5.5/mingw492_32/include/QtCore -Itmp/cpu -I../../../../Qt/5.5/mingw492_32/mkspecs/win32-g++  -o tmp/cpu/release/blocking_queue.o blocking_queue.cpp
In file included from ../../3rdparty/windows/boost/exception/diagnostic_information.hpp:17:0,
                 from ../../3rdparty/windows/boost/exception/all.hpp:15,
                 from ../backtrace/exceptionassert.h:7,
                 from blocking_queue.cpp:2:
../../3rdparty/windows/boost/exception/info.hpp: In member function 'virtual boost::shared_ptr<boost::exception_detail::error_info_base> boost::exception_detail::error_info_container_impl::get(const boost::exception_detail::type_info_&) const':
../../3rdparty/windows/boost/exception/info.hpp:102:28: error: use of deleted function 'boost::shared_ptr<boost::exception_detail::error_info_base>::shared_ptr(const boost::shared_ptr<boost::exception_detail::error_info_base>&)'
                     return p;
                            ^
```

The boost version doesn't look... recent. Maybe it needs to be updated to work with C++11?

**Comment by gustafsson** [comment]
Yes, I'd say that would be a good idea. Boost 1.47 is 4 years old :)

Most of boost are headers only libraries but we need to build boost
serialization and boost date_time (se boostlib in freq-windows) for the
specific compiler in use as well (due to different ABIs). They can be
downloaded for different versions of VC (link on boost homepage) but with
mingw you have to build them yourself:
http://stackoverflow.com/questions/13256788/building-boost-1-52-with-mingw
tors 24 sep 2015 kl. 23:47 skrev David Hesselbom notifications@github.com:

**Comment by davidhesselbom** [comment]
> MinGW doesn't have support for threads.

The "MinGW Installation Manager" allows to install packages for MinGW. One of these is called `mingw32-libpthreadgc` which 

> seeks to provide a freely available and high-quality implementation of pthreads for Windows.  Pthreads is an API for writing multithreaded applications following the POSIX standard. There are two mingw32 versions of the pthread-w32 runtime library: the standard one, provided by this package, is called libpthreadgc but may also be referred to as 'libpthread'.  The non-standard one uses C++ exception handling, and is called libpthreadgce. (Note that the standard library may be used successfully with C++ code; indeed, on most *nix platorms the system pthreads implementation follows the behavior of mingw32-libpthreadgc, and NOT the behavior of the 'GCE' version).

How much of the problem would that package solve? I'm not sure what `std::mutex` and `std::thread` are and how they compare to POSIX thread stuff. Maybe they're the same thing?

**Comment by gustafsson** [comment]
pthreads is an API for concurrency (i.e threading and mutexing), std::mutex
/ std::thread is another API for concurrency. It is possible to create a
wrapper for one of them using the other. I don't think the package you
mention includes a wrapper but I might be wrong. The win32 API contains yet
another API for concurrency which meganz/mingw-std-threads is wrapping to
implement the std::thread/mutex API.

mingw-w64 builds contain std::mutex and std::thread by default. see
http://mingw-w64.org/doku.php/download#mingw-builds

lör 26 sep 2015 21:20 David Hesselbom notifications@github.com skrev:

**Comment by davidhesselbom** [comment]
Okay, so, use mingw-w64 -> get rid of mingw-w32 -> profit? Works for me.

**Comment by gustafsson** [comment]
"should" work :)

lör 26 sep 2015 21:39 David Hesselbom notifications@github.com skrev:

**Comment by davidhesselbom** [comment]
> mingw-w64 builds contain std::mutex and std::thread by default

It also contains `libsndfile` and `zlib`. Should those be removed from the windows submodule, if we decide to go with mingw-w64? And, regardless, should `omp` be removed?

**Comment by gustafsson** [comment]
Neither libsndfile, zlib nor boost serialization are used by Freq (yet).
And I think that the only parts of boost date_time still in use are header
only.

Omp; remove if it makes things difficult, but I'm not certain it will.

Note that changing the compiler also requires a rebuild of Qt.

Also note that we haven't yet seen if the mingw version in the Qt folder is built with support for std concurrency or not. So I think we should upgrade boost in winlib first (and skip boostlib for now).

**Comment by davidhesselbom** [comment]
Okay, sure.

**Comment by gustafsson** [comment]
gustafsson/freq-windows@0200d6f7e3b076809c8249711dc471d529b3e347 now has boost 1.59 header only

**Comment by davidhesselbom** [comment]
```
In file included from thread_pool.cpp:1:0:
thread_pool.h: In member function 'void JustMisc::thread_pool::addTask(std::packaged_task<F()>&&)':
thread_pool.h:35:18: warning: lambda capture initializers only available with -std=c++1y or -std=gnu++1y
                 [task=std::move(task)] () mutable
                  ^
thread_pool.cpp: In lambda function:
thread_pool.cpp:40:78: error: 'pthread_setname_np' was not declared in this scope
                         pthread_setname_np(pthread_self(), ss.str ().c_str ());
                                                                              ^
```

Are there other submodules I need to update?

**Comment by davidhesselbom** [comment]
Or does this error message mean we're making progress? :) I don't think I've seen this particular one before...

**Comment by gustafsson** [comment]
seems like pthread_setname_np doesn't work on mingw. it's only useful to
make debugging prettier and doesn't affect any functionality. you'll have
to adjust the #ifdef around it to skip mingw.

buildflags might need -std=c++1y or better yet -std=c++14 for mingw to get
rid of that warning

sön 20 dec 2015 21:53 David Hesselbom notifications@github.com skrev:

**Comment by davidhesselbom** [comment]
Should `-std=c++1y` or `-std=c++14` be added to `QMAKE_CXXFLAGS` for all configurations, then?

Also,

``` cpp
#ifdef __GNUC__
                    {
                        stringstream ss;
                        ss << (name?name:"thread_pool") << " " << i << "/" << n;
#ifdef __clang__
                        pthread_setname_np(ss.str ().c_str ());
#else
                        pthread_setname_np(pthread_self(), ss.str ().c_str ());
#endif
                    }
#endif
```

Where and how are `__GNUC__` and `__clang__` set and what's the corresponding one for MinGW? Or does MinGW count as GNUC?

**Comment by gustafsson** [comment]
these are defined by the compiler, **GNUC** is not defined by MSVC. For
mingw: #ifdef **MINGW32**

we should probably stick to using qmake CONFIG+=c++11 or c++14 instead of
using std=... (see top of buildflags.prf).

the warning is disabled on osx by
QMAKE_CXXFLAGS += -Wno-c++1y-extensions
you could try something similar for mingw.

sön 20 dec 2015 22:27 David Hesselbom notifications@github.com skrev:

**Comment by davidhesselbom** [comment]
> we should probably stick to using qmake CONFIG+=c++11 or c++14 instead of using std=... (see top of buildflags.prf).

Maybe I misunderstand, but the string `std` doesn't actually occur a single time in `buildflags.prf` ([see for yourself](https://github.com/gustafsson/freq/blob/develop/features/buildflags.prf)). So should I add `CONFIG += c++11` somewhere near the top?

I'm not really concerned about the warning right now. I included it in case it was relevant, but if you think it can safely be disabled, I'll just ignore it for the time being.

**Comment by davidhesselbom** [comment]
Anyway, we're clearly not using `c++11`, since I have to specify it, but if we're not using `c++11`, then why does this

```
!c++11 {
    error("Use \"CONFIG += c++11 buildflags\" instead of \"CONFIG += buildflags\"")
}
```

not generate an error message?

**Comment by gustafsson** [comment]
exactly, std=... should not occur anywhere. we should rely on config+=c++11
and buildflags.prf ensures that we are indeed using config+=c++11.

mån 21 dec 2015 09:42 David Hesselbom notifications@github.com skrev:

**Comment by gustafsson** [comment]
the warning is not about not using c++11, but about using c++1y features
although only specifying c++11. it can be ignored

mån 21 dec 2015 09:55 Johan Gustafsson johan.b.gustafsson@gmail.com skrev:

**Comment by davidhesselbom** [comment]
I still don't understand... this output can be found in the appveyor log:

```
g++ -c -pipe -fno-keep-inline-dllexport -O2 -Wall -Wextra -std=c++0x
```

But this doesn't seem to happen:

```
!c++11 {
    error("Use \"CONFIG += c++11 buildflags\" instead of \"CONFIG += buildflags\"")
}
```

What does this mean? Are we using a c++11 compiler, but the c++0x standard library?

**Comment by gustafsson** [comment]
c++0x is in this regard the exact same thing as c++11

mån 21 dec 2015 10:01 David Hesselbom notifications@github.com skrev:

**Comment by davidhesselbom** [comment]
What just happened to the AppVeyor integration...?

https://ci.appveyor.com/project/gustafsson/freq/history

**Comment by davidhesselbom** [comment]
The AppVeyor integration is back. Did you change some setting or something, somewhere? Regardless, can you try restarting the build on AppVeyor? It seems to be stuck "waiting."

**Comment by davidhesselbom** [comment]
Or maybe you could "invite" me to the project on AppVeyor, if that's doable.

**Comment by davidhesselbom** [comment]
I was hoping making a dummy commit would make AppVeyor move on, but the new build job is now "queued"; probably waiting for the previous one to complete before it can begin, so please abort the old one if you can, or restart the old one and abort this one.

**Comment by davidhesselbom** [comment]
Oh, it ran, after all, just took a few minutes :D

```
backtrace.cpp:14:22: fatal error: execinfo.h: No such file or directory
 #include <execinfo.h>
                      ^
compilation terminated.
```

Now what?

**Comment by davidhesselbom** [comment]
I mean, yeah, obviously `execinfo.h` needs to be somewhere the compiler can find it, but as usual, I have no idea where I should look for it, which version I need, or whether we should simply add another `ifndef` for the `include` on Windows because the library doesn't exist there, or anything. I'm sure you're as frustrated about this as I am, though, but what can you do...

**Comment by davidhesselbom** [comment]
Bump :)

**Comment by davidhesselbom** [comment]
Yay, we made it into gpumisc!

```
tmp/cpu/release/geometricalgebra.o geometricalgebra.cpp
In file included from GLvector.h:4:0,
                 from geometricalgebra.h:4,
                 from geometricalgebra.cpp:1:
gl.h:28:46: fatal error: GL/glew.h: No such file or directory
 # include <GL/glew.h> // glew.h includes gl.h
```

Another (I seem to remember seeing these a long time ago) glew import error - and I've forgotten how to fix it...

**Comment by davidhesselbom** [comment]
Any ideas?

**Comment by davidhesselbom** [comment]
Apparently, something about "QOpenGLFunctions" instead of legacy OpenGL. No easy task, either.

**Comment by gustafsson** [comment]
yep, QOpenGLFunctions is the way to go. Qt5 is essentially incompatible with glew. There are workarounds but I'd prefer leaving glew behind. I think the instances where we need to replace direct calls to calls through an instance of  QOpenGLFunctions is fairly limited. Most OpenGL calls will work without the wrapper (I think ;))

**Comment by gustafsson** [comment]
i.e QOpenGLFunctions is "the wrapper" I'm referring to

**Comment by davidhesselbom** [comment]
> There are workarounds but I'd prefer leaving glew behind.

Sure. I suspect migrating to QOpenGLFunctions will take another few years at this rate and with my level of expertise in the subject matter, though... :/

**Comment by davidhesselbom** [comment]
So, I guess you could just as well merge this. I'm afraid I won't be much help with QOpenGLFunctions anytime soon, and this PR at least gets past building Backtrace...

**Comment by aveminus** [comment]
I am trying to make it work with QT5_4 VS2013 . I see you guys have not updated the `*.pro` files in the lib directory. They are still pointing to the old directory `../sonicawe-winlib` instead of  `../../3rdparty/windows/`. Also update the `sawelibs.prf` towards the end section of the file to point to  `../../3rdparty/windows/`. That fixes all the GL/glew complains. 
And I still have more errors of different kinds :) ha ha ha

**Comment by gustafsson** [comment]
@aveminus Could you make a new PR that builds on appveyor so that we could help out to figure out what's wrong?

**Comment by gustafsson** [comment]
Cool though if QT5 works with glew in VS2013! I had thought glew and QT were incompatible since QT5.

**Pull request merged**
