### PR TITLE
Fixed things in .pro files.

### PR DESCRIPTION
**Pull request by davidhesselbom**

### CODE REVIEW

**Comment by davidhesselbom** [comment]
Hmm, does this need fixing in the other `.pro` files, too? What about the ones in `tests/integration`, are those still in use?

**Comment by gustafsson** [comment]
Lovely. And yes, this applies to quickbase.bro (stupid dummy name that I never bothered changing) and src.pro. The `tests/integration` projects are somewhat outdated. But yes, it applies to them as well.

**Comment by davidhesselbom** [comment]
I don't see anything in `quickbase.pro` I can fix...

In `src.pro`, there's this:

```
   win32:CONFIG -= embed_manifest_dll
   win32:CONFIG += embed_manifest_exe
```

Is this also VS specific?

**Comment by gustafsson** [comment]
Ah, of course. Quickbase.pro has never been built on windows, yet :)

No, the manifest is windows specific, not VS specific.
ons 23 sep 2015 kl. 22:01 skrev David Hesselbom notifications@github.com:

**Comment by davidhesselbom** [comment]
Do you need me to fix `sonicawe.prf`, the test projects, and/or possibly something more before you merge this?

**Comment by gustafsson** [comment]
Na, let's take one thing at a time.

**Comment by gustafsson** [comment]
Fixes #14

**Pull request merged**
