### PR TITLE
Updated to new windows libs directory in project files and added other projects to sonicawe.sln

### PR DESCRIPTION
**Pull request by aveminus**
Made changes in *.pro file to reflect on the new location of windows libs. Does not fix all issue yet. I am using VS 2013 and QT5_4 VS2013 build.

### CODE REVIEW

**Comment by aveminus** [comment]
Fixes all the glew.h not found errors.

**Comment by aveminus** [comment]
Quick question. Should I be using sonicawe.pro or should I be using quickbase.pro to do the build?

**Comment by davidhesselbom** [comment]
Nice work, but I think we need to be moving away from glew anyway. @gustafsson?

**Comment by aveminus** [comment]
Yes definitely. But it might take while to replace them with Qt alternatives. For now, I just want it to build :)

**Comment by davidhesselbom** [comment]
Fair enough. I'm just worried that getting it to build with glew might take a while and it'd be a waste of time if we're not going to use it anyway... 

Do you know if the build errors we're seeing now (`glframebuffer.cpp:192:63: error: 'glBlarrgh' was not declared in this scope`) are because of missing includes or because we actually _need_ to migrate to the Qt GL alternative?

**Comment by aveminus** [comment]
Yeah It would be better if we spend time trying to get rid of GLEW. Those gl function call errors are also defined in `<QOpenGLFunctions>`. We can try removing the GLEW header includes.

**Comment by davidhesselbom** [comment]
Now that Vulkan is out, though, maybe we should try to get things working with that instead? ;)

https://blog.qt.io/blog/2016/02/16/the-qt-company-joins-khronos-group-and-promotes-vulkan/

**Comment by gustafsson** [comment]
Afaik glew and QT are incompatible since QT5. Not sure why, just that the headers aren't meant to be used at the same time. I think that it would still work though if glew and QT5-calls are not mixed in the same file. gpumisc/gl.h previously included both so a hack would be to not us this file an go straight for glew.h in those few files that needs glew (I might be wrong but I think it's just a few).

Yet another approach would be to use QOpenGLFunctions through a singleton. QOpenGLFunctions claims to be context-specific but I have doubts that it actually is :)

Another option is to replace the glew-calls with QT5 objects that encapsulate equivalent functionality.

@davidhesselbom Does Vulkan replace glew, QOpenGLFunctions, or is it a different approach?

@aveminus If you can make a separate appveyor build for VS2013 we can help each other out to figure out what's holding back the build.

**Comment by davidhesselbom** [comment]
The API is supposedly meant to replace OpenGL everywhere, afaik, and everyone involved seems pretty excited about it. I don't think OpenGL support will be removed anytime soon, though! I mentioned it because Qt themselves did, and because of the performance boosts it has given other applications.

#### Of course, it would be better to get something _working_, however slow, and improve from there.

It's just I don't know how much work will be needed to get QOpenGLFunctions working, and I think you will eventually want to start using Vulkan anyway.

**Comment by gustafsson** [comment]
@aveminus So there are two projects in this repo.
- Sonic AWE, which uses glew and a lot of 3rd party stuff
- Freq, which uses (almost) only the Qt Quick part of the Qt framework

About using QOpenGLFunctions:
Replacing `glFunction(...)`
with 

```
QOpenGLFunctions *glFuncs = QOpenGLContext::currentContext()->functions();
glFuncs->glFunction(...)
```

should do the trick

---

Thanks for the updated paths!

**Comment by gustafsson** [comment]
Like this: 14a8a677c264af200f6659a908a1256b62bc3712

Which at least builds:
https://ci.appveyor.com/project/gustafsson/freq

**Comment by davidhesselbom** [comment]
> QOpenGLFunctions *glFuncs = QOpenGLContext::currentContext()->functions();
> glFuncs->glFunction(...)

Well, that was a lot easier than I thought it would be :D

> Which at least builds:

Oh, you had me going there, I thought the whole project built now >< But it's a big improvement! How far would you guess we've come in making freq build? About halfway, less, more?

**Comment by gustafsson** [comment]
More than halfway!

Den ons 9 mar 2016 07:19David Hesselbom notifications@github.com skrev:

**Comment by davidhesselbom** [comment]
Yay! So what's the next step?

**Comment by gustafsson** [comment]
Doing the same thing for glstate.cpp and others, and build libflac for freq-windows

**Comment by davidhesselbom** [comment]
What's libflac and why do we need it?

EDIT: Okay, it's a library for encoding and decoding FLAC. Makes sense. It's not a format I use a lot, though, so I could live without it.

**Comment by gustafsson** [comment]
To open .ogg and .flac files.

Den ons 9 mar 2016 20:29David Hesselbom notifications@github.com skrev:

**Comment by gustafsson** [comment]
@davidhesselbom it's currently the only format supported by Freq

**Comment by davidhesselbom** [comment]
No wav or aiff?

**Comment by gustafsson** [comment]
Nope. It might be easy to get those working on windows though, Qt has some [audio decoding support](http://wiki.qt.io/Qt_5.5.0_Multimedia_Backends#Supported_audio_decoding_features_by_backend). Which I fiddled with a little bit.

**Pull request merged**
