### PR TITLE
GlState

### PR DESCRIPTION
**Pull request by davidhesselbom**
Let's see whether this fixes anything... time and AppVeyor will tell!

### CODE REVIEW

**Comment by davidhesselbom** [comment]
To someone who knows C++, what I just did might look stupid, but hell, it was worth a try!

**Comment by davidhesselbom** [comment]
That's odd, adding `GlState` before the `::` in glstate.cpp actually seems to have worked. But why? I can't help but feel I've fixed a problem that shouldn't have occurred in the first place.

**Comment by gustafsson** [comment]
By using ::x you specify that you refer to x in the global namespace. GlState::x is x in GlState, not in the global namespace.

**Comment by davidhesselbom** [comment]
Okay, but how come those functions were referring to things in the global namespace instead of the `GlState` namespace, where they could be found? I'm getting similar errors now when buildling `glframebuffer.cpp`. Should I make the same "fixes" there? Are these files not used when building the osx/ios versions?

**Comment by gustafsson** [comment]
they were referring to stuff in the global namespace. because opengl
functions normally reside in the global namespace. but we want to instead
use the opengl functions from QGlFunctions instead of those from the global
namespace.

Den ons 9 mar 2016 21:09David Hesselbom notifications@github.com skrev:

**Comment by davidhesselbom** [comment]
Ah...

**Comment by davidhesselbom** [comment]
`glframebuffer.cpp` can't build because it can't find `glDeleteFramebuffers`, and neither can I.

**Comment by gustafsson** [comment]
http://doc.qt.io/qt-5/qglfunctions.html#glDeleteFramebuffers

Den tors 10 mar 2016 21:03David Hesselbom notifications@github.com skrev:

**Comment by davidhesselbom** [comment]
Well, that didn't work. What do I need to do to use QGLFunctions::glDeleteFramebuffers?

**Comment by gustafsson** [comment]
I explain how to use QGLFunctions [here](https://github.com/gustafsson/freq/pull/17#issuecomment-194094207)

GlState uses QGLFunctions as of 264de4a20805443034e52a7885c6b664d0fab6d8

You might want to rebase 9e670c0750aa1c997928fb69463347b01b132446 onto appveyor.

**Comment by davidhesselbom** [comment]
Oh, right. Thanks!

**Pull request closed without merging**
