### PR TITLE
WiP - enable AppVeyor

### PR DESCRIPTION
**Pull request by davidhesselbom**
# DO NOT MERGE (yet), DO NOT CLOSE

This pull request will be used as a sandbox for making freq build on AppVeyor. It will contain dirty commits and other bad things, because afaik there's no other way to test if things run on AppVeyor. Commits need to go into an open pull request or AppVeyor will not trigger. 

[This page](http://www.appveyor.com/docs/build-configuration) should contain everything we need to know to get this to work.

### CODE REVIEW

**Comment by gustafsson** [comment]
Roger that. Let me know what you need

**Comment by davidhesselbom** [comment]
Actually, go ahead and merge this to stop getting error messages from AppVeyor whenever you push new commits. I'll open a new pull request for the sandbox. Same thing with #6.

**Comment by davidhesselbom** [comment]
Actually, this build already tells you interesting stuff about missing `LICENSE`, whatever that means, so it's already useful! A little bit, at least.

**Comment by gustafsson** [comment]
Cool, fire away. The note about a missing LICENSE is because a couple of .pro files are erroneously referencing such a file even though the different static libraries doesn't have any of their own and are covered by the repository license.

**Pull request merged**
